CREATE OR REPLACE FUNCTION "RECORD_HIGH_TEMPERATURES_FOR_DATE"("D" DATE)
RETURNS TABLE ("EVENT_DATE" DATE, "CITY" VARCHAR(16777216), "TEMPERATURE" NUMBER(38,0))
LANGUAGE SQL
AS '
    select d, ''New York'', 65.0
    union all
    select d, ''Los Angeles'', 69.0
    ';